- .github/workflows/release.yml
- package.json
Adds a nice little green checkmark with provenance information on the npmjs website. See https://docs.npmjs.com/generating-provenance-statements.
> fix: add provenance for published package

- .c8rc.json
- package-lock.json
- package.json
- src/helpers/github.cjs
- src/reporters/mocha.cjs
- test/github.test.js
This means that at report generation time the github context will sourced. Helps with data consistency/accuracy.
> fix: add GitHub context in reporter

- .c8rc.json
- .github/workflows/ci.yml
- .gitignore
- .mocharc.json
- package-lock.json
- package.json
- src/reporters/helpers.cjs
- src/reporters/mocha.cjs
- src/reporters/playwright.js
- test.json
- test/integration/configs/mocha.json
- test/integration/configs/playwright.js
- test/integration/mocha.test.js
- test/integration/playwright.test.js
- test/unit/github.test.js
This adds a reporter for `playwright` that's inline with the mocha reporter. The main difference is playwright supports multi-browser execution so the the optional `browser` input is actually emitted.
Not the first part of each test name is the project name. I had projects called `chromium`, `firefox` and `webkit` for testing.
```json
{
"reportId": "3bb7187d-c2a8-4e70-9227-469af272cdf3",
"reportVersion": 1,
"summary": {
"operatingSystem": "windows",
"framework": "playwright",
"started": "2023-12-21T18:50:45.938Z",
"totalDuration": 21348,
"status": "passed",
"countPassed": 6,
"countFailed": 0,
"countSkipped": 3,
"countFlaky": 3
},
"details": [
{
"name": "chromium > reporter > skipped test",
"started": "2023-12-21T18:50:45.968Z",
"location": "test/integration/playwright.test.js",
"retries": …
```
> Add playwright reporter

- src/reporters/mocha.cjs
> fix: report options reading for mocha

- test.json
This got accidently checked in with the playwright reporter. Not used at all.
> fix: remove unused file

- package.json
- src/reporters/mocha.cjs
- src/reporters/playwright.js
- test/integration/mocha-1.test.js
- test/integration/mocha-2.test.js
- test/integration/playwright-1.test.js
- test/integration/playwright-2.test.js
Resolves #45. When a test consistently fails on reties we don't want to count it as flaky. Right now it was being included in that count. This removes it from that count so a test is only "flaky" if it reties and eventually succeeds. I also added some consistently failing tests to the suite of tests so we can better test this set-up. Eventually will add output validation tests as well.
> fix: flaky test count

- .mocharc.json
- package.json
- test/integration/report-validation.test.js
Doesn't actually do any validation. Just putting the set-up in place. Plan is to move the schema validation helper from the `*-action` repository into here so we can run schema validation and then do some specific value checks.
> Add test report generation validation

- .gitignore
- package-lock.json
- package.json
- src/reporters/helpers.cjs
- src/reporters/mocha.cjs
- src/reporters/playwright.js
- test/integration/configs/d2l-test-reporting.config.json
- test/integration/configs/mocha.cjs
- test/integration/configs/playwright.js
Resolves https://github.com/Brightspace/test-reporting-node/issues/39. This adds a simple configuration file for specifying the `type`, `tool` and `experience` via a set of defaults as well as a set of `overrides` that are defined by a `pattern`. The patterns are globs and the first pattern to match will be the one chosen using the defaults as a last option fallback. Eventually I want to use `ajv` to validate the configuration file that's loaded but I want to refactor how we build and validate the report first. Need to move the validation of the report output from the `action` to this repo. Example config
```json
{
"type": "Integration",
"experience": "Test Framework",
"tool": "Test Reporting",
"overrides": [
{
"pattern": "*/**/mocha-1.test.js",
"experience": "Mocha 1 Test Framework", …
```
> fix: add config file for specifying things like `type`, `tool` and `experience`

- src/reporters/helpers.cjs
- src/reporters/mocha.cjs
- src/reporters/playwright.js
- test/integration/configs/d2l-test-reporting.config.json
This fixes the issue with including `minimatch`. Not a huge fan of mixing `commonjs` and `modules` but due to the mocha reporter needing to be `commonjs` it's kind of unavoidable. Might be worth introducing a build step at some point to output something that works for both automatically but fort now this work.
> fix: clean-up usage of minimatch

- .c8rc.json
- .github/workflows/ci.yml
- package-lock.json
- package.json
- src/helpers/github.cjs
- src/helpers/report.cjs
- src/helpers/schema.cjs
- src/reporters/playwright.js
- test/integration/report-validation.test.js
- test/unit/github.test.js
This moves the validation over from [Brightspace/test-reporting-action](https://github.com/Brightspace/test-reporting-action) to here so we can use it for report generation validation as well as have 1 spot for report schema and format helpers. Once this is in I'll move the action over to using the new helpers. I still want to rework this to be a bit more organized but this at least get's it all in 1 spot. Partially takes care of https://github.com/Brightspace/test-reporting-action/issues/53.
> fix: move validation over from action

- src/reporters/mocha.cjs
- src/reporters/playwright.js
This doesn't count flaky tests as passed. Keeps the data consistent with playwright and makes it easier to understand overall test counts.
> fix: flaky count

- src/reporters/helpers.cjs
- src/reporters/mocha.cjs
- src/reporters/playwright.js
Get's us closer to being able to use the `merge-reports` workflow for `playwright`. Right now this still fails to get `defaultBrowserType` due to https://github.com/microsoft/playwright/issues/29174.
> fix: add workaround for getting project data

- src/reporters/helpers.cjs
- src/reporters/mocha.cjs
- src/reporters/playwright.js
- test/integration/configs/mocha.cjs
- test/integration/configs/playwright.js
Makes some stuff more consistent. Shouldn't affect downstreams since they all use defaults.
> fix: clean-up some naming

- src/reporters/playwright.js
- test/integration/data/config/playwright.js
Not the best but add workaround for not being able to get access to the browser information in all cases. Requires adding metadata directly. This adds a protentional for this getting out of sync.
> fix: add workaround for playwright use information being missing

- test/integration/data/config/playwright.js
- test/integration/data/playwright.global.setup.js
- test/integration/data/playwright.global.teardown.js
- test/integration/data/playwright.setup.js
- test/integration/data/playwright.teardown.js
- test/integration/report-validation.test.js
Adds examples of both options laid out [here](https://playwright.dev/docs/test-global-setup-teardown). The first option using `dependencies` results in additional "fake" tests in the output. Using option 2 does not have this problem. There doesn't seem to be a nice way to detect option 1 and remove those tests from the output.
> Add example of playwright global setup/teardown to tests

- .c8rc.json
- .github/workflows/ci.yml
- src/reporters/mocha.cjs
- src/reporters/playwright.js
- src/reporters/web-test-runner.js
- test/integration/data/config/mocha.cjs
- test/integration/data/config/playwright.js
- test/integration/data/config/web-test-runner.js
- test/integration/data/mocha-1.test.js
- test/integration/report-validation.test.js
Resolves #94. Will warning when reporter is set to verbose mode. Added coverage report since coverage locally is different then in GitHub actions due to a few things not being available locally.
> fix: warning when in verbose mode about missing taxonomy

- .c8rc.json
- src/helpers/github.cjs
- src/helpers/report.cjs
- src/helpers/schema.cjs
- src/reporters/helpers.cjs
- test/unit/github.test.js
- test/unit/report.test.js
This adds better error messages as well as schema validation for report configuration files. The configs must result in all combinations containing a version of `type`, `test` and `experience`. As an example the following config is not valid since there is no fallback for `tool` and it's not defined in the override so the resulting taxonomy is incomplete.
```json
{
"experience": "Test Framework",
"type": "integration",
"overrides": [
{
"pattern": "*/**/mocha-1.test.js",
"type": "ui",
}
]
}
```
The error messaging isn't perfect but it's good enough for our purposes for now. Will product stuff like the below.
```
Error: report does not conform to schema
Details: the string at '/details/0/name' must match pattern "^(?!\s).+(?<!\s)$"
Current value: "test suite > flaky test "
```
It gives a …
> fix: add report configuration schema and improve error messaging

- package-lock.json
- src/helpers/schema.cjs
- src/reporters/helpers.cjs
- src/reporters/mocha.cjs
- src/reporters/playwright.js
- src/reporters/web-test-runner.js
- test/integration/data/config/d2l-test-reporting.json
- test/integration/data/mocha-3.test.js
- test/integration/data/playwright-3.test.js
- test/integration/data/web-test-runner-3.test.js
- test/integration/report-validation.test.js
This is mainly so we can ignore global set-up and teardown type of files. I'm a bit on the fence about adding this. I can create a disconnect between the overall status and the actual test statuses (could have all tests show status `passed` but overall show `failed` if the failed test was ignored). I'm hoping to use this very sparingly. It is useful to sometimes ignore files but I'm hoping to use this very sparingly. Resolves #105.
I'm looking for opinions on this one if anyone has any.
> fix: add ability to ignore files for report

- .c8rc.json
- .github/workflows/ci.yml
- .gitignore
- .licensechecker.json
- d2l-test-reporting.config.json
- package-lock.json
- package.json
- reporter.config.js
- src/helpers/report.cjs
- src/helpers/schema.cjs
- src/reporters/testcafe.js
- test/integration/data/config/mocha.cjs
- test/integration/data/config/playwright.js
- test/integration/data/config/testcafe.cjs
- test/integration/data/config/web-test-runner.js
- test/integration/data/testcafe-1.test.js
- test/integration/data/testcafe-2.test.js
- test/integration/data/testcafe-3.test.js
- test/integration/report-validation.test.js
This reporter isn't perfect but it's at a point where I think we can start using it and figure out some of the fringe cases later. In order for this reporter to work with `testcafe` you'll have4 to use the [`testcafe-reporter-custom`](https://www.npmjs.com/package/testcafe-reporter-custom) which let's you inject a reporter from any path instead of needing to release a package with a specific name on npm. Resolves #98.
> fix: add `testcafe` reporter

- src/reporters/web-test-runner.js
I can't get the browser to fail to start again but this should take care of the issue. It will result in an incomplete report but it will properly represent what ran. Resolves #127.
> fix: null exception when browser fails to launch

- src/reporters/testcafe.js
The `alias` field includes command line parameters.
> fix: switch to use browser name field for testcafe

- src/helpers/report-configuration.cjs
This took me 4 hours to figure out. I hate JavaScript sometimes.  Need to add a test that covers this. Will do that in another PR.
> fix: don't return an object in a constructor

- test/integration/data/mocha-1.test.js
- test/integration/data/mocha-2.test.js
- test/integration/data/mocha-3.test.js
- test/integration/data/playwright-1.test.js
- test/integration/data/playwright-2.test.js
- test/integration/data/playwright-3.test.js
- test/integration/data/web-test-runner-1.test.js
- test/integration/data/web-test-runner-2.test.js
- test/integration/data/web-test-runner-3.test.js
Note there are different behaviours depending on framework. Right now this is how it lands.
* `mocha`
* before/after all/each are all not included in reported times
* Will look into reporting it separately or adding it to test times depending on what we decide
* `playwright`
* before/after all are not included in reported times, before/after each are included in reported times
* Probably fine since the before/after each make sense to be part of the test times
* Will look into reporting it separately
* `@web/test-runner`
* before/after all/each are all included in reported times due to how it reports it's timings
* No nice way around this I've found so far, reported time is of all tests run for that worker
* `testcafe`
* Don't really care since we're killing it, didn't look into it and …
> Add before/after all/each to test data

- .github/dependabot.yml
These could end up not having us on them due to ignoring the `package-lock.json` file. Doing this makes sure we are on all things dependabot opens.
> Always add reviewers for dependabot PR's

- package-lock.json
- package.json
Added #183 so I don't forget. For some reason npm dedupes typescript incorrectly cause of `testcafe` dependencies.
> Put in temporary fix to get auto updates working again

- .c8rc.json
- src/helpers/github.cjs
- src/helpers/object.cjs
- src/helpers/report-builder.cjs
- src/helpers/report-configuration.cjs
- src/helpers/report.cjs
- src/helpers/schema.cjs
- test/integration/report-validation.test.js
- test/unit/github.test.js
- test/unit/report.test.js
This reworks how we handle reports entirely and adds a top level `Report` object that we can load, validate and upgrade reports with. By default it will always validate the incoming report, upgrade it to the latest report version then validate it again. Right now we only have 1 version but this is going to change soon. Having this kind of pipelines upgrades will be handy for keeping backways compatibility is needed. It also allows us to deprecate older version of reports with a nice interface/error messaging. The `ReportBuilder` should always be built to output the latest report format.
> Rework how we do report handling

- src/helpers/report.cjs
- test/unit/report.test.js
Add helper to pull context back out from report in the same format as the `getContext` github helper. Useful for downstreams.
> feat: add context getter

- .github/workflows/release.yml
This will dispatch an update to the 'test-reporting-action' whenever a `main` branch update occurs. Saves me having to open PR's for this manually.
> fix: dispatch updates

- package-lock.json
- package.json
- schemas/report/v2.json
- src/helpers/report.cjs
- src/helpers/schema.cjs
- test/integration/data/validation/test-report-mocha.js
- test/integration/data/validation/test-report-playwright.js
- test/integration/data/validation/test-report-testcafe.js
- test/integration/data/validation/test-report-web-test-runner.js
- test/integration/report-validation.test.js
- test/unit/report.test.js
This adds the v2 schema and implements the auto upgrade path in the `Report` construct. Right now the `ReportBuilder` doesn't output the new `v2` format as I want to roll that out separately. This allows for the additional data wanted in #162, #156, #149 and #29 to be added (all net new data is optional in `v2`). This new data will come once the `ReportBuilder` is upgraded (will be done in another PR). Tests have been updated to test against the `v2` format. Want to look at running tests against `v1` as well possibly so I've left the partial test data in for now. Will do more test updates in a future PR.
This will require changes in the action so the automatic PR that will get opened will fail CI. That's ok though. I'll make the adjustments there.
BREAKING CHANGE: Add a `v2` schema of the …
> feat: add report v2 schema

- schemas/report/v2.json
This was incorrect. Updating to include proper properties. I'm not bumping the schema version here since nothing is emitting or consuming any error property stuff yet.
> fix: v2 schema incorrect `error` property

- src/helpers/report-builder.cjs
- src/reporters/mocha.cjs
- src/reporters/web-test-runner.js
- test/integration/data/mocha-1.test.js
- test/integration/data/mocha-2.test.js
- test/integration/data/mocha-3.test.js
- test/integration/data/playwright-1.test.js
- test/integration/data/playwright-2.test.js
- test/integration/data/playwright-3.test.js
- test/integration/data/web-test-runner-1.test.js
- test/integration/data/web-test-runner-2.test.js
- test/integration/data/web-test-runner-3.test.js
- test/integration/report-validation.test.js
This removed the implicit setting of the detail duration values to 0 in the constructor. Will cause invalid report if those values don't get set anywhere. Better for tracking down issues. Tests were starting to take too long as well so minimized time waiting.
> fix: make setting of `duration` of `0` explicit for some reporters

- src/helpers/report-builder.cjs
Just had unnecessary code. All the helpers end in `return this;` so anything using a helper can just do `return this.[helper]`.
> fix: remove unneeded code

- .github/workflows/update-dependencies.yml
Now that this workflow is mainly automated and we will get added to stuff only on errors let's increase how often it happens. Keeps things fresh.
> Run updates more frequently

- .github/dependabot.yml
There are issues with `eslint` updates for version `9` and greater. Ignore them for now to stop spam Prs
> Add ignore rule for `eslint` for now

- README.md
I'll go and update all the different config files to use the new terms now too
> Update readme to include link to testing definitions confluence page 

- src/helpers/report-builder.cjs
If the config fails to load it's `null`, add some `null` checks to avoid downstream error messages being throw. Noticed this in https://github.com/Brightspace/playwright-ui-automation/pull/1641.
> fix: don't throw errors if config is not loaded

- src/reporters/mocha.cjs
- src/reporters/playwright.js
- src/reporters/web-test-runner.js
This is mainly to handle issues with config file loading. This will just not generate a report if it fails to load the config or find any of the needed start data. Found this while doing some other integrations.
https://desire2learn.atlassian.net/browse/QE-251
> fix: handle issues with initializing the report builder (QE-251)

- src/reporters/playwright.js
Adjustment made from [this suggestion](https://github.com/Brightspace/test-reporting-node/pull/370#discussion_r1825055178). Also removed unneeded intermediate variable `overrideStatus`.
> fix: make status checking code smaller

- eslint.config.js
- src/helpers/report-builder.cjs
- src/helpers/strings.cjs
- src/reporters/mocha.cjs
- src/reporters/playwright.js
- src/reporters/web-test-runner.js
- test/integration/data/tests/mocha/reporter-1.test.js
- test/integration/data/tests/mocha/reporter-2.test.js
- test/integration/data/tests/mocha/reporter-3.test.js
- test/integration/data/tests/playwright/reporter-1.test.js
- test/integration/data/tests/playwright/reporter-2.test.js
- test/integration/data/tests/playwright/reporter-3.test.js
- test/integration/data/tests/web-test-runner/reporter-1.test.js
- test/integration/data/tests/web-test-runner/reporter-2.test.js
- test/integration/data/tests/web-test-runner/reporter-3.test.js
This should help with integration of older/less well written test names.
> fix: trim test name path parts

- .github/workflows/release.yml
When using `secrets` using `github.actor` over `github.triggering_actor` properly reflects the permission to `secrets`. If the triggering actor is some user but the first actor that tiggered the workflow was `dependabot` then `secrets` will not be available. Only really a problem for re-runs buit might as well avoid it.
> Fix usage of `triggering_actor`

- package-lock.json
- package.json
- schemas/report/v1.json
- schemas/report/v2.json
- src/helpers/report-configuration.cjs
- src/helpers/report.cjs
- src/helpers/schema.cjs
- test/unit/report.test.js
Switch to use [`ajv-errors`](https://www.npmjs.com/package/ajv-errors) instead of rolling our own error message handling. This adds simple messages to the weird pattern ones to give more context. We can add more messaging as we find we need it.
https://desire2learn.atlassian.net/browse/QE-581
> feat: add in custom error handling

- eslint.config.js
- package-lock.json
- package.json
Stops the mixing of `then`/`async`/`await` and just fully disallows `then` chaining. Forces more "modern" syntax.
https://desire2learn.atlassian.net/browse/QE-634
> Disallow promise chaining

- src/reporters/playwright.js
For some reason we've started observing negative duration values from playwright. This is resulting in not sending data to the backend. For now let's just zero out the negative durations until we can figure out what's going on.
https://desire2learn.atlassian.net/browse/QE-662
> fix: mitigate negative duration issues
