.github/workflows/ci.yml
.github/workflows/update-dependencies.yml

Switch to public runners

---

.eslintrc.json
package-lock.json
package.json

This is mainly to test the release workflow.

fix: update eslint config

---

.c8rc.json
.github/dependabot.yml
package-lock.json
package.json
src/reporters/mocha.cjs

fix: remove need for chalk

---

.c8rc.json
src/reporters/helpers.cjs
src/reporters/mocha.cjs
src/reporters/playwright.js

Just makes the output easier to read/diff if comparing reports.

fix: add ordering of fields for consistent output

---

.gitignore
package-lock.json
package.json
src/reporters/mocha.cjs
src/reporters/playwright.js
test/integration/configs/mocha.cjs
test/integration/configs/mocha.json

Just use `randomUUID` instead from nodes `crypto` library..

fix: remove need for `uuid`

---

.github/workflows/ci.yml

Resolves #30. Adds the generated report for each reporter in a comment on the PR so it can be inspected. Eventually want to add tests to catch formatting issues but this seems like a good thing to have regardless.

Post comment with generated report

---

.github/workflows/ci.yml
package.json

Split coverage generation into its own command

---

src/reporters/playwright.js

Should have known better then to just use the playwright test result status directly. Map to the values we want to track. Playwright can return [more specific statuses](https://playwright.dev/docs/api/class-testresult#test-result-status) then we care about.

fix: playwright reporter

---

.github/workflows/release.yml

Secrets not available for dependabot triggered runs.

Skip when dependabot

---

README.md

Adjust section to match command nomenclature

---

src/reporters/playwright.js

Makes it easier to visually see the project name, also closer to the output of other reporters for playwright.

fix: better playwright test name

---

package-lock.json
package.json
test/integration/configs/playwright.js
test/integration/report-validation.test.js

Add full report validation for `mocha` and `playwright`. Want to do some refactoring so these will be helpful to make sure I generate the same report information.

Add better report validation

---

.github/workflows/ci.yml
package-lock.json
package.json
src/reporters/playwright.js
src/reporters/web-test-runner.js
test/integration/configs/d2l-test-reporting.config.json
test/integration/configs/web-test-runner.js
test/integration/report-validation.test.js
test/integration/web-test-runner-1.test.js
test/integration/web-test-runner-2.test.js

This still has some problems and has caused me to question a few things but it overall does work. This doesn't include browser information yet (trying to figure out where to get it).

Initial `@web/test-runner` reporter

---

.c8rc.json
src/helpers/github.cjs
src/helpers/schema.cjs
test/unit/github.test.js
test/unit/report.test.js

Added some more testing as well.

fix: improve schema set-up

---

README.md
package.json
test/integration/data/config/mocha.cjs

Basic documentation on how to use reporter.

fix: add documentation on reporter usage

---

README.md

Just adding a couple sample config files to the readme

Adding documentation for reporting config file

---

src/reporters/playwright.js
test/integration/data/config/playwright.js

Fix getting of browser data. Won't throw errors when metadata not available now.

fix: browser type detection

---

src/helpers/schema.cjs

Will make it easier to pull the schema out in the future so it can be shared.

fix: update to use purely json schema constructs

---

src/reporters/mocha.cjs

fix: mocha clean-up

---

.github/workflows/ci.yml

Just some clean-up. Also adds details to the summary of the GitHub run now.

Better PR comment

---

src/helpers/report.cjs
src/reporters/mocha.cjs

This is needed mainly for the `TestCafe` reporter.

Add ability to have custom writer for report data

---

.github/workflows/release.yml

Not really a new release but want to test the release token.

fix: update release token

---

package.json
src/helpers/report-configuration.cjs
src/helpers/report.cjs
src/reporters/mocha.cjs
src/reporters/playwright.js
src/reporters/testcafe.js
src/reporters/web-test-runner.js

Want to use this in an action. Also just kinda nice to wrap up the config stuff in a class.

Expose report config construct

---

.github/dependabot.yml
.github/workflows/update-dependencies.yml

Slowing down the cadence of update. Less noise

Only do auto updates on weekly

---

.github/dependabot.yml
package-lock.json
package.json

This will force a 1.0.0 release. I'll update everyone after doing this.
BREAKING CHANGE: require playwright 1.42.1

feat: require playwright 1.42.1

---

.github/workflows/update-dependencies.yml

Requires https://github.com/Brightspace/repo-settings/pull/1828.

Add slack alerting on auto update issues

---

package-lock.json
package.json

The dependabot update wasn't quite right.

Fix dev dependencies

---

.c8rc.json
package.json
schemas/report-configuration/v1.json
schemas/report/v1.json
src/helpers/github.cjs
src/helpers/report-configuration.cjs
src/helpers/report.cjs
src/helpers/schema.cjs

This should just make it simpler to make new schemas.

feat: extract schemas into files

---

src/helpers/report-builder.cjs
src/helpers/report-configuration.cjs
src/helpers/system.cjs
test/integration/report-validation.test.js

Rename some internal utilities

---

package-lock.json
package.json

Backporting #190. I also just want to make sure this works (having maintanence branches)

fix: update minimum `playwright` version

---

src/helpers/report.cjs

Missed this during the initial pass. Need to add some more unit/integration tests around the LMS stuff. Will look at that in a future PR. Want to add a bunch more testing.

fix: lms property upgrade

---

src/helpers/report-builder.cjs
src/helpers/schema.cjs
src/reporters/mocha.cjs
src/reporters/playwright.js
src/reporters/testcafe.js
src/reporters/web-test-runner.js
test/integration/report-validation.test.js

This switched the report builder to output natively the v2 report format. This does not include sending of any new fields yet.
Resolves #29.

feat: report builder outputs report v2 natively

---

src/helpers/report-builder.cjs
test/integration/data/mocha-1.test.js
test/integration/data/mocha-2.test.js
test/integration/data/mocha-3.test.js
test/integration/data/playwright-1.test.js
test/integration/data/playwright-2.test.js
test/integration/data/playwright-3.test.js
test/integration/data/playwright.setup.js
test/integration/data/playwright.teardown.js
test/integration/data/testcafe-1.test.js
test/integration/data/testcafe-2.test.js
test/integration/data/testcafe-3.test.js
test/integration/data/web-test-runner-1.test.js
test/integration/data/web-test-runner-2.test.js
test/integration/data/web-test-runner-3.test.js
test/integration/report-validation.test.js

This also adds some tests to catch this issue in the future.

fix: incorrect `final` duration

---

src/reporters/mocha.cjs

Also to test my automation workflows.

fix: detail call chaining in mocha reporter

---

.editorconfig

This is mostly a dummy change to test something.

fix: clean-up editor config

---

README.md

Add release versioning info

---

.github/workflows/ci.yml
README.md
package-lock.json
package.json

One more thing to help keep stuff "clean". Used it in a few other repos.

Add `editorconfig-checker`

---

eslint.config.js
package-lock.json
package.json
src/helpers/github.cjs
src/helpers/object.cjs
src/helpers/report-builder.cjs
src/helpers/report-configuration.cjs
src/helpers/report.cjs
src/helpers/schema.cjs
src/helpers/strings.cjs
src/helpers/system.cjs
src/reporters/mocha.cjs
test/integration/data/configs/mocha.cjs

This adds the `import` plugins and also better sets up stuff to make the `use strict` stuff not required.

fix: more adjustments to eslint config

---

.github/workflows/ci.yml

Hard-coded paths and such for now but this now allows us to host generated coverage reports.
https://desire2learn.atlassian.net/browse/QE-569

Switch to hosted coverage report

---

schemas/report/v2.json

https://desire2learn.atlassian.net/browse/QE-147

Removing unused `error` field, will add in new schema

---

src/reporters/playwright.js

Will merge this once the issue is filed at the playwright folks and the infrastructure failure notification stuff is in place.
https://desire2learn.atlassian.net/browse/QE-662
Reverts Brightspace/test-reporting-node#478

Revert "fix: mitigate negative duration issues"

---

README.md
docs/report-format.md

All minor fixes with the help of AI!
https://desire2learn.atlassian.net/browse/QE-1159

Adjust some documentation
